#!/usr/bin/env bash
# Tell the story of passwd

while IFS=: read -r username password user_id group_id info home_dir shell;do
	echo "The user $username is part of the $group_id gang, lives in $home_dir and rides $shell. $user_id's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd
