#!/usr/bin/env bash
# Manages the manage_my_process script


argv1=$1
tmpfile="/var/run/my_process.pid"
start_process(){
	./manage_my_process &
	echo "$!" > "$tmpfile"
}
stop_process(){
	#kill "$(cat "$tmpfile")"
	sudo pkill -f "./manage_my_process"
	rm "$tmpfile"
}

case "$argv1" in
	start) echo "manage_my_process started"
		start_process
		;;
	stop) echo "manage_my_process stopped"
		stop_process
		;;
	restart) echo "manage_my_process restarted"
		stop_process
		start_process
		;;
	*) echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
